AWSTemplateFormatVersion: '2010-09-09'
Description: Networking 101 Template

Parameters:
##Naming
  Project:
    Description: Please enter a descirption for this network
    Type: String
    Default: "Networking 101"
##VPC
  VPCCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 172.15.0.0/20
  PresentationSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private presentation subnet in the first Availability Zone
    Type: String
    Default: 172.15.0.0/25
  PresentationSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private presentation subnet in the second Availability Zone
    Type: String
    Default: 172.15.0.128/25
  ApplicationSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private application subnet in the first Availability Zone
    Type: String
    Default: 172.15.4.0/24
  ApplicationSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private application subnet in the second Availability Zone
    Type: String
    Default: 172.15.5.0/24
  DataSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private data subnet in the first Availability Zone
    Type: String
    Default: 172.15.2.0/25
  DataSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private data subnet in the second Availability Zone
    Type: String
    Default: 172.15.2.128/25

Resources:
##Base VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref Project, VPC]]
        - Key: Project
          Value: !Ref Project
##IPv6 Allocation
  VPCIpv6CIDR:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      VpcId: !Ref VPC
      AmazonProvidedIpv6CidrBlock: true
##Subnets
  PresentationSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: VPCIpv6CIDR
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PresentationSubnet1CIDR
      Ipv6CidrBlock:
        Fn::Sub:
          - "${VPCPart}${SubnetPart}"
          - SubnetPart: '00::/64'
            VPCPart: !Select [ 0, !Split [ '00::/56', !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]]]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref Project, PresentationSubnet1]]
        - Key: Project
          Value: !Ref Project
        - Key:  Tier
          Value: Presentation
  PresentationSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn: VPCIpv6CIDR
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PresentationSubnet2CIDR
      Ipv6CidrBlock:
        Fn::Sub:
          - "${VPCPart}${SubnetPart}"
          - SubnetPart: '10::/64'
            VPCPart: !Select [ 0, !Split [ '00::/56', !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]]]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref Project, PresentationSubnet2]]
        - Key: Project
          Value: !Ref Project
        - Key:  Tier
          Value: Presentation
  ApplicationSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: VPCIpv6CIDR
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref ApplicationSubnet1CIDR
      Ipv6CidrBlock:
        Fn::Sub:
          - "${VPCPart}${SubnetPart}"
          - SubnetPart: '20::/64'
            VPCPart: !Select [ 0, !Split [ '00::/56', !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]]]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref Project, ApplicationSubnet1]]
        - Key: Project
          Value: !Ref Project
        - Key:  Tier
          Value: Application
  ApplicationSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn: VPCIpv6CIDR
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref ApplicationSubnet2CIDR
      Ipv6CidrBlock:
        Fn::Sub:
          - "${VPCPart}${SubnetPart}"
          - SubnetPart: '30::/64'
            VPCPart: !Select [ 0, !Split [ '00::/56', !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]]]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref Project, ApplicationSubnet2]]
        - Key: Project
          Value: !Ref Project
        - Key:  Tier
          Value: Application
  DataSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: VPCIpv6CIDR
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref DataSubnet1CIDR
      Ipv6CidrBlock:
        Fn::Sub:
          - "${VPCPart}${SubnetPart}"
          - SubnetPart: '40::/64'
            VPCPart: !Select [ 0, !Split [ '00::/56', !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]]]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref Project, DataSubnet1]]
        - Key: Project
          Value: !Ref Project
        - Key:  Tier
          Value: Data
  DataSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn: VPCIpv6CIDR
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref DataSubnet2CIDR
      Ipv6CidrBlock:
        Fn::Sub:
          - "${VPCPart}${SubnetPart}"
          - SubnetPart: '50::/64'
            VPCPart: !Select [ 0, !Split [ '00::/56', !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]]]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref Project, DataSubnet2]]
        - Key: Project
          Value: !Ref Project
        - Key:  Tier
          Value: Data
##Networking
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref Project, RouteTable]]
        - Key: Project
          Value: !Ref Project
        - Key:  Tier
          Value: Networking
  PresentationSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PresentationSubnet1
  PresentationSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PresentationSubnet2
  ApplicationSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref ApplicationSubnet1
  ApplicationSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref ApplicationSubnet2
  DataSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref DataSubnet1
  DataSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref DataSubnet2
##FlowLogs
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14
      LogGroupName:
        !Join
        - '-'
        - - !Select
            - '0'
            - !Split [ ' ', !Ref Project ]
          - !Select
            - '1'
            - !Split [ ' ', !Ref Project ]
          - 'VPCFlowLogs'

  IAMFlowLogPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Resource: !GetAtt CloudWatchLogGroup.Arn
      Roles:
        - Ref: IAMFlowLogRole
  IAMFlowLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - vpc-flow-logs.amazonaws.com
            Action:
              - sts:AssumeRole
  VPCFlowLogs:
    Type: AWS::EC2::FlowLog
    Properties:
      LogGroupName: !Ref CloudWatchLogGroup
      ResourceId: !Ref VPC
      ResourceType: VPC
      TrafficType: ALL
      LogDestinationType: cloud-watch-logs
      DeliverLogsPermissionArn: !GetAtt IAMFlowLogRole.Arn

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC
  VPCCIDR:
    Value: !Ref VPCCIDR
  VPCIpv6CIDR:
    Value: !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]
  PresentationSubnets:
    Description: A list of the presentation subnets
    Value: !Join [ ",", [ !Ref PresentationSubnet1, !Ref PresentationSubnet2]]
  PresentationSubnet1:
    Description: A reference to the first presentation subnet
    Value: !Ref PresentationSubnet1
  PresentationSubnet2:
    Description: A reference to the second presentation subnet
    Value: !Ref PresentationSubnet2
  ApplicationSubnets:
    Description: A list of the application subnets
    Value: !Join [ ",", [ !Ref ApplicationSubnet1, !Ref ApplicationSubnet2]]
  ApplicationSubnet1:
    Description: A reference to the first application subnet
    Value: !Ref ApplicationSubnet1
  ApplicationSubnet2:
    Description: A reference to the second application subnet
    Value: !Ref ApplicationSubnet2
  DataSubnets:
    Description: A list of the data subnets
    Value: !Join [ ",", [ !Ref DataSubnet1, !Ref DataSubnet2]]
  DataSubnet1:
    Description: A reference to the first data subnet
    Value: !Ref DataSubnet1
  DataSubnet2:
    Description: A reference to the second data subnet
    Value: !Ref DataSubnet2
  AvailabilityZones:
    Description: The Availability zones used
    Value: !Join [ ",", [ !GetAtt DataSubnet1.AvailabilityZone, !GetAtt DataSubnet2.AvailabilityZone]]
  PresentationSubnet1CIDR:
    Value: !Ref PresentationSubnet1CIDR
  PresentationSubnet2CIDR:
    Value: !Ref PresentationSubnet2CIDR
  ApplicationSubnet1CIDR:
    Value: !Ref ApplicationSubnet1CIDR
  ApplicationSubnet2CIDR:
    Value: !Ref ApplicationSubnet2CIDR
  DataSubnet1CIDR:
    Value: !Ref DataSubnet1CIDR
  DataSubnet2CIDR:
    Value: !Ref DataSubnet2CIDR
  PresentationSubnet1IPv6CIDR:
    Value: !Select [ 0, !GetAtt PresentationSubnet1.Ipv6CidrBlocks ]
  PresentationSubnet2IPv6CIDR:
    Value: !Select [ 0, !GetAtt PresentationSubnet2.Ipv6CidrBlocks]
  ApplicationSubnet1IPv6CIDR:
    Value: !Select [ 0, !GetAtt ApplicationSubnet1.Ipv6CidrBlocks]
  ApplicationSubnet2IPv6CIDR:
    Value: !Select [ 0, !GetAtt ApplicationSubnet2.Ipv6CidrBlocks]
  DataSubnet1IPv6CIDR:
    Value: !Select [ 0, !GetAtt DataSubnet1.Ipv6CidrBlocks]
  DataSubnet2IPv6CIDR:
    Value: !Select [ 0, !GetAtt DataSubnet2.Ipv6CidrBlocks]
  PrivateRouteTable:
    Value: !Ref PrivateRouteTable